### ISSUE TITLE
Stats broken if hotspot has been added w/o owner

### ISSUE THREAD

**Issue by Neilburt21** [jamiew/helium-discord-bot#6] opened 2021-06-23 00:34 UTC
```
helium-hotspots: GET https://api.helium.io/v1/hotspots/11fMRZhjyx9bvujDUz1qpg3Cx4jGN6JQAeUCtrJzLu81pdeCmtY
helium-hotspots: GET https://api.helium.io/v1/hotspots/11fMRZhjyx9bvujDUz1qpg3Cx4jGN6JQAeUCtrJzLu81pdeCmtY/rewards/sum?max_time=2021-06-23T00:24:09.296Z&min_time=2021-06-22T00:24:09.296Z
(node:2928) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'padEnd' of undefined
    at Object.fetchEverything (C:\Users\burtm\Desktop\DB\hotspots.js:139:87)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.<anonymous> (C:\Users\burtm\Desktop\DB\bot.js:34:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jamiew** [comment] 2021-06-23 01:52
I think you caught us mid-documentation update. You need to use the `hotspot add [address]` commands interactively with the bot first

What do you get if you ask `hotspot config`? (feel free to censor actual addresses)

**Comment by Neilburt21** [comment] 2021-06-23 02:16
I actually just deleted .padEnd(10) from Line 139, 86 and it started working. BUT while I have your attention. a monthly stat would be cool if you added that too!

**Comment by Neilburt21** [comment] 2021-06-23 02:17
and for the record... it was adding address just fine. Just couldn't convert the data.

**Comment by jamiew** [comment] 2021-06-23 02:19
got it, did you just use `hotspot add {address}` and not `hotspot add {address} {owner_display_name}}`? think that might be the bug

**Comment by Neilburt21** [comment] 2021-06-23 02:23
I did both but non worked

**Comment by jamiew** [comment] 2021-06-23 15:35
thx, think I know what the issue is, we'll take a look

**Comment by jamiew** [comment] 2021-07-20 21:54
This is fixed now

**Closed by jamiew** 2021-07-20 21:54 UTC
Labels: bug
